"use client";

import { AlertTriangle, BookOpen, Check, Copy, ExternalLink, FileDown, LoaderCircle, Network, PenLine, RotateCcw, ShieldCheck, Sparkles } from "lucide-react";
import { useState } from "react";
import type { RewriteMode, RewriteResult, ScanReport, SentenceAnalysis } from "@/src/core/types";

type Tab = "overlap" | "sources" | "signals" | "council" | "improve" | "citation" | "report";
const tabs: Array<{ id: Tab; label: string }> = [{id:"overlap",label:"Trùng lặp"},{id:"sources",label:"Nguồn"},{id:"signals",label:"AI Writing"},{id:"council",label:"AI Council"},{id:"improve",label:"Cải thiện"},{id:"citation",label:"Citation"},{id:"report",label:"Báo cáo"}];

export function AssistantPanel({ report, selected, rewrite, rewriting, writingSample, onWritingSample, onRewrite, onAccept, onPrint, onDownload }: { report?: ScanReport; selected?: SentenceAnalysis; rewrite?: RewriteResult; rewriting: boolean; writingSample: string; onWritingSample: (value: string) => void; onRewrite: (mode: RewriteMode) => void; onAccept: () => void; onPrint: () => void; onDownload: () => void }) {
  const [tab, setTab] = useState<Tab>("overlap");
  const [mode, setMode] = useState<RewriteMode>("deep");
  return <aside className="no-print hidden border-l border-[var(--line)] bg-[var(--surface)] lg:flex lg:min-h-0 lg:flex-col"><div className="flex h-[58px] shrink-0 items-center justify-between border-b border-[var(--line)] px-5"><div className="flex items-center gap-2"><Sparkles size={17} className="text-[var(--violet)]" /><strong className="text-sm">Trợ lý nguyên bản</strong></div>{report && <span className="rounded-full bg-[var(--brand-soft)] px-2.5 py-1 text-[10px] font-bold text-[var(--brand)]">ĐÃ PHÂN TÍCH</span>}</div>
    <div className="scrollbar-thin flex shrink-0 gap-1 overflow-x-auto border-b border-[var(--line)] px-3 py-2">{tabs.map((item) => <button key={item.id} onClick={() => setTab(item.id)} className={`whitespace-nowrap rounded-lg px-2.5 py-2 text-[11px] font-bold ${tab === item.id ? "bg-[var(--surface-2)] text-[var(--ink)]" : "text-[var(--muted)] hover:text-[var(--ink)]"}`}>{item.label}</button>)}</div>
    <div className="scrollbar-thin min-h-0 flex-1 overflow-y-auto p-5">{!report ? <Empty /> : tab === "overlap" ? <Overlap sentence={selected} /> : tab === "sources" ? <Sources report={report} /> : tab === "signals" ? <Signals report={report} /> : tab === "council" ? <Council report={report} /> : tab === "improve" ? <Improve selected={selected} mode={mode} setMode={setMode} rewrite={rewrite} rewriting={rewriting} writingSample={writingSample} onWritingSample={onWritingSample} onRewrite={onRewrite} onAccept={onAccept} /> : tab === "citation" ? <Citation selected={selected} /> : <ReportActions report={report} onPrint={onPrint} onDownload={onDownload} />}</div>
  </aside>;
}

function Empty() { return <div className="flex h-full flex-col items-center justify-center text-center"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-[var(--brand-soft)] text-[var(--brand)]"><Sparkles size={23} /></span><h2 className="serif mt-5 text-xl">Sẵn sàng phân tích</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Chạy kiểm tra để xem nguồn, lý do và đề xuất theo từng câu.</p></div>; }

function Overlap({ sentence }: { sentence?: SentenceAnalysis }) {
  if (!sentence) return <Hint text="Chọn một câu đã đánh dấu để xem chi tiết." />;
  return <div className="space-y-5"><Section title="Câu hiện tại"><p className="serif text-[15px] leading-7">{sentence.text}</p></Section><Section title="Vấn đề"><p className="text-sm leading-6 text-[var(--muted)]">{sentence.reason}</p></Section><div className="grid grid-cols-3 gap-2">{[["Exact",sentence.exactScore],["Fuzzy",sentence.fuzzyScore],["Semantic",sentence.semanticScore]].map(([label,value]) => <div key={String(label)} className="rounded-xl bg-[var(--surface-2)] p-3 text-center"><b className="serif block text-xl">{value}%</b><span className="text-[10px] text-[var(--muted)]">{label}</span></div>)}</div>{sentence.sourceText && <Section title="Đoạn tương đồng"><p className="line-clamp-6 text-[13px] leading-6 text-[var(--muted)]">{sentence.sourceText}</p></Section>}<Section title="Hành động gợi ý"><p className="text-sm leading-6 text-[var(--muted)]">{sentence.suggestedAction}</p></Section></div>;
}

function Sources({ report }: { report: ScanReport }) { return report.sources.length ? <div className="space-y-3">{report.sources.map((source) => <a href={source.url} target="_blank" rel="noreferrer" key={source.id} className="group block rounded-2xl border border-[var(--line)] p-4 hover:border-[var(--brand)]"><div className="flex items-start justify-between gap-2"><div><b className="line-clamp-2 text-sm leading-5">{source.title}</b><span className="mt-1 block text-[11px] text-[var(--brand)]">{source.domain}</span></div><ExternalLink size={14} className="shrink-0 text-[var(--muted)]" /></div><p className="mt-3 line-clamp-3 text-[12px] leading-5 text-[var(--muted)]">{source.snippet || "Nguồn đã được xác minh từ kết quả truy xuất."}</p></a>)}</div> : <Hint icon={BookOpen} text="Không tìm thấy nguồn đáng tin cậy. Hệ thống sẽ không tạo URL thay thế." />; }

function Signals({ report }: { report: ScanReport }) {
  const analysis = report.aiWriting;
  const label = analysis.label === "human" ? "Thiên về người viết" : analysis.label === "mixed" ? "Có dấu hiệu phối hợp" : analysis.label === "ai" ? "Nghi vấn AI cao" : "Chưa đủ dữ liệu";
  return <div>
    <div className="rounded-2xl bg-[var(--amber-soft)] p-4">
      <div className="flex items-start justify-between gap-3"><div><span className="text-[11px] font-bold uppercase tracking-[.12em] text-[var(--amber)]">Chỉ báo tổng hợp</span><strong className="serif mt-2 block text-3xl font-normal">{analysis.score}%</strong></div>{analysis.confidence !== undefined && <span className="rounded-full bg-[var(--surface)] px-2.5 py-1 text-[10px] font-bold text-[var(--muted)]">Tin cậy {analysis.confidence}%</span>}</div>
      <p className="mt-2 text-sm font-bold">{label}</p>
      {analysis.flaggedShare !== undefined && <p className="mt-1 text-[11px] text-[var(--muted)]">Phần văn bản detector đánh dấu: {analysis.flaggedShare}%</p>}
      <p className="mt-3 text-[12px] leading-5 text-[var(--muted)]">{analysis.disclaimer}</p>
    </div>
    {analysis.agreement && <div className={`mt-3 rounded-xl border p-3 ${analysis.agreement.status === "weak" ? "border-[var(--amber)] bg-[var(--amber-soft)]" : "border-[var(--line)]"}`}><div className="flex items-center justify-between text-[12px]"><b>Đồng thuận detector</b><span>{analysis.agreement.score}% · {analysis.agreement.completedDetectors} bộ máy</span></div><p className="mt-2 text-[11px] leading-4 text-[var(--muted)]">{analysis.agreement.message}</p></div>}
    {analysis.provenance && <div className="mt-5"><h3 className="mb-2 text-[11px] font-bold uppercase tracking-[.14em] text-[var(--muted)]">Bằng chứng quá trình</h3><div className="rounded-2xl border border-[var(--line)] p-4"><div className="flex items-center justify-between"><b className="text-sm">Độ mạnh {analysis.provenance.evidenceStrength}%</b><span className="rounded-full bg-[var(--surface-2)] px-2 py-1 text-[10px] font-bold">{analysis.provenance.status === "available" ? "ĐÃ GHI NHẬN" : analysis.provenance.status === "partial" ? "MỘT PHẦN" : "KHÔNG CÓ"}</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-[11px]"><span>Nhập trực tiếp <b className="float-right">{analysis.provenance.typedShare}%</b></span><span>Dán vào <b className="float-right">{analysis.provenance.pastedShare}%</b></span><span>Nhập tệp <b className="float-right">{analysis.provenance.importedShare}%</b></span><span>AI hỗ trợ <b className="float-right">{analysis.provenance.aiAssistedShare}%</b></span></div><p className="mt-3 text-[11px] leading-4 text-[var(--muted)]">{analysis.provenance.summary} Dữ liệu phiên trình duyệt chưa phải chữ ký pháp lý.</p></div></div>}
    {analysis.detectors && <div className="mt-5"><h3 className="mb-2 text-[11px] font-bold uppercase tracking-[.14em] text-[var(--muted)]">Bộ máy tham gia</h3><div className="space-y-2">{analysis.detectors.map((detector) => <div key={detector.id} className="rounded-xl border border-[var(--line)] p-3"><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${detector.status === "completed" ? "bg-[var(--brand)]" : detector.status === "failed" ? "bg-[var(--coral)]" : "bg-[var(--line)]"}`} /><b className="flex-1 text-[12px]">{detector.name}</b><span className="text-[12px] font-bold">{detector.score !== undefined ? `${detector.score}%` : "—"}</span></div><p className="mt-2 text-[11px] leading-4 text-[var(--muted)]">{detector.detail}</p></div>)}</div></div>}
    {analysis.segments && analysis.segments.length > 0 && <div className="mt-5"><h3 className="mb-2 text-[11px] font-bold uppercase tracking-[.14em] text-[var(--muted)]">Đoạn cần xem lại</h3><div className="space-y-2">{[...analysis.segments].sort((left, right) => right.score - left.score).slice(0, 6).map((segment) => <div key={segment.id} className="rounded-xl bg-[var(--surface-2)] p-3"><div className="flex items-center justify-between text-[11px]"><b>{segment.label === "ai" ? "Nghi vấn AI" : segment.label === "mixed" ? "Có phối hợp" : segment.label === "human" ? "Thiên về người viết" : "Chưa kết luận"}</b><span>{segment.score}% · tin cậy {segment.confidence}%</span></div><p className="mt-2 line-clamp-3 text-[11px] leading-4">{segment.text}</p><p className="mt-2 text-[10px] leading-4 text-[var(--muted)]">{segment.reason}</p></div>)}</div></div>}
    <div className="mt-5 space-y-4">{analysis.signals.map((signal) => <div key={signal.label}><div className="flex justify-between text-[12px]"><b>{signal.label}</b><span>{signal.score}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[var(--line)]"><div className="h-full rounded-full bg-[var(--amber)]" style={{width:`${signal.score}%`}} /></div><p className="mt-1.5 text-[11px] leading-4 text-[var(--muted)]">{signal.detail}</p></div>)}</div>
  </div>;
}

function Council({ report }: { report: ScanReport }) {
  if (!report.council) return <Hint icon={Network} text="AI Council đang tắt để kiểm soát chi phí. Đặt AI_COUNCIL_ENABLED=true và cấu hình OpenAI API key để bật bảy chuyên gia phản biện." />;
  const roleNames: Record<string, string> = { "document-analyst": "Document Analyst", "similarity-critic": "Similarity Critic", "source-auditor": "Source Auditor", "citation-guardian": "Citation Guardian", "writing-coach": "Writing Coach", "risk-reviewer": "Risk Reviewer", "quality-reviewer": "Quality Reviewer" };
  return <div className="space-y-5"><div className="rounded-2xl bg-[var(--violet-soft)] p-4"><div className="flex items-center justify-between"><span className="text-[11px] font-bold uppercase tracking-[.12em] text-[var(--violet)]">Hội đồng chuyên gia</span><b className="serif text-2xl font-normal">{report.council.confidence}%</b></div><p className="mt-3 text-[13px] leading-6 text-[var(--muted)]">{report.council.summary}</p></div><Section title="Agent đã tham gia"><div className="space-y-2">{report.council.agents.map((agent) => <div key={agent.role} className="flex items-center gap-2 text-[12px]"><span className={`h-2 w-2 rounded-full ${agent.status === "completed" ? "bg-[var(--brand)]" : "bg-[var(--coral)]"}`} /><span className="flex-1 font-semibold">{roleNames[agent.role] ?? agent.role}</span><span className="text-[var(--muted)]">{agent.findingCount} phát hiện</span></div>)}</div></Section>{report.council.priorities.length > 0 && <Section title="Ưu tiên xử lý"><ol className="space-y-2">{report.council.priorities.map((item, index) => <li key={item} className="flex gap-2 text-[12px] leading-5"><b className="text-[var(--violet)]">{index + 1}.</b><span>{item}</span></li>)}</ol></Section>}{report.council.disagreements.length > 0 && <Section title="Điểm chưa đồng thuận"><div className="space-y-2">{report.council.disagreements.map((item) => <p key={item} className="flex gap-2 text-[12px] leading-5 text-[var(--muted)]"><AlertTriangle size={14} className="mt-0.5 shrink-0 text-[var(--amber)]" />{item}</p>)}</div></Section>}</div>;
}

function Improve({ selected, mode, setMode, rewrite, rewriting, writingSample, onWritingSample, onRewrite, onAccept }: { selected?: SentenceAnalysis; mode: RewriteMode; setMode: (mode: RewriteMode) => void; rewrite?: RewriteResult; rewriting: boolean; writingSample: string; onWritingSample: (value: string) => void; onRewrite: (mode: RewriteMode) => void; onAccept: () => void }) { return <div>{!selected ? <Hint text="Chọn một câu cần cải thiện trong vùng highlight." /> : <><label className="text-[12px] font-bold uppercase tracking-[.12em] text-[var(--muted)]">Chế độ chỉnh sửa<select value={mode} onChange={(event) => setMode(event.target.value as RewriteMode)} className="mt-2 w-full rounded-xl border border-[var(--line)] bg-[var(--surface)] p-3 text-sm font-semibold text-[var(--ink)]"><option value="light">Sửa nhẹ</option><option value="deep">Viết lại sâu</option><option value="personal">Theo phong cách của tôi</option><option value="academic">Hỗ trợ học thuật</option></select></label>{mode === "personal" && <label className="mt-4 block text-[12px] font-bold uppercase tracking-[.12em] text-[var(--muted)]">Đoạn văn thật của bạn<textarea value={writingSample} onChange={(event) => onWritingSample(event.target.value)} placeholder="Dán 2–3 đoạn do chính bạn viết để hệ thống học nhịp câu và cách chuyển ý…" className="mt-2 min-h-28 w-full resize-y rounded-xl border border-[var(--line)] bg-[var(--surface)] p-3 text-sm font-normal leading-6 text-[var(--ink)]" /></label>}<button disabled={rewriting || (mode === "personal" && writingSample.trim().length < 40)} onClick={() => onRewrite(mode)} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-[var(--violet)] px-4 py-3 text-sm font-bold text-white disabled:opacity-50">{rewriting ? <LoaderCircle size={16} className="animate-spin" /> : <PenLine size={16} />} Tạo đề xuất</button>{rewrite && <div className="mt-5 space-y-4"><Section title="Bản đề xuất"><p className="serif text-[15px] leading-7">{rewrite.rewrittenText}</p></Section><div className={`rounded-xl p-3 ${rewrite.factCheck.safe ? "bg-[var(--brand-soft)]" : "bg-[var(--coral-soft)]"}`}><div className="flex items-center gap-2 text-[12px] font-bold">{rewrite.factCheck.safe ? <Check size={15} className="text-[var(--brand)]" /> : <AlertTriangle size={15} className="text-[var(--coral)]" />}{rewrite.factCheck.safe ? "Dữ kiện và citation được bảo toàn" : "Cần kiểm tra khác biệt dữ kiện"}</div>{!rewrite.factCheck.safe && <p className="mt-2 text-[11px] leading-5 text-[var(--muted)]">Thiếu: {rewrite.factCheck.missingFacts.join(", ") || "—"} · Thêm: {rewrite.factCheck.addedFacts.join(", ") || "—"}</p>}</div><button onClick={onAccept} disabled={!rewrite.factCheck.safe} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[var(--brand)] px-4 py-3 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-40"><Check size={16} /> Chấp nhận thay đổi</button></div>}</>}</div>; }

function Citation({ selected }: { selected?: SentenceAnalysis }) { return <div><div className="flex items-center gap-3 rounded-2xl bg-[var(--brand-soft)] p-4"><ShieldCheck className="text-[var(--brand)]" /><div><b className="text-sm">Citation Guard</b><p className="mt-1 text-[11px] text-[var(--muted)]">APA · MLA · IEEE · Vancouver</p></div></div>{selected ? <div className="mt-5"><Section title="Trạng thái câu">{selected.citationProtected ? <p className="flex items-center gap-2 text-sm text-[var(--brand)]"><Check size={16} /> Đã khóa trích dẫn khi viết lại</p> : <p className="text-sm leading-6 text-[var(--muted)]">Không phát hiện citation trong câu đã chọn. Nếu luận điểm dựa trên một nguồn cụ thể, hãy bổ sung nguồn trước khi xuất bản.</p>}</Section></div> : <Hint text="Chọn một câu để kiểm tra citation." />}</div>; }

function ReportActions({ report, onPrint, onDownload }: { report: ScanReport; onPrint: () => void; onDownload: () => void }) { return <div><div className="rounded-2xl border border-[var(--line)] p-4"><span className="text-[11px] font-bold uppercase tracking-[.12em] text-[var(--muted)]">Originality Report</span><strong className="serif mt-3 block text-4xl font-normal">{report.metrics.originality}%</strong><p className="mt-2 text-[12px] leading-5 text-[var(--muted)]">Báo cáo gồm overview, nguồn, passages, citation, AI-writing signals và đề xuất.</p></div><button onClick={onPrint} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-[var(--brand)] px-4 py-3 text-sm font-bold text-white"><FileDown size={16} /> In / lưu PDF</button><button onClick={onDownload} className="mt-2 flex w-full items-center justify-center gap-2 rounded-xl border border-[var(--line)] px-4 py-3 text-sm font-bold"><Copy size={16} /> Tải báo cáo Word</button></div>; }

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h3 className="mb-2 text-[11px] font-bold uppercase tracking-[.14em] text-[var(--muted)]">{title}</h3><div className="rounded-2xl border border-[var(--line)] p-4">{children}</div></section>; }
function Hint({ text, icon: Icon = RotateCcw }: { text: string; icon?: typeof RotateCcw }) { return <div className="rounded-2xl border border-dashed border-[var(--line)] p-5 text-center"><Icon size={20} className="mx-auto text-[var(--muted)]" /><p className="mt-3 text-[12px] leading-5 text-[var(--muted)]">{text}</p></div>; }
